# Generated by Django 5.1.1 on 2024-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(null=True, upload_to='movie_images/'),
        ),
    ]
