# Generated by Django 5.1.1 on 2024-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_video_movie_image_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(default='anything', upload_to='movie_images/'),
        ),
    ]
